version: "3.9"
services:
  verthem-db:
    image: postgres
    restart: always
    container_name: verthem-db
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: password
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres

volumes:
  postgres: